modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL-3.0-only"
issueTrackerURL = "https://github.com/MajorBonghits/ModernCompanions/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}; original: justinwon777"
description = "${description}"


[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "curios"
type = "optional"
versionRange = "${curios_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "waystones"
type = "optional"
versionRange = "${waystones_file_version_id}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "wthit"
type = "optional"
versionRange = "${wthit_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "balm"
type = "optional"
versionRange = "${balm_file_version_id}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "badpackets"
type = "optional"
versionRange = "${badpackets_version}"
ordering = "NONE"
side = "BOTH"